# 服务端口号(本身是一个 web 项目)
server:
  port: 8081

# 起个名字作为服务名称(该服务注册到 eureka 注册中心的名称，比如商品服务)
spring:
  application:
    name: app-commodity
  security:
    # 配置用户的账号信息
    user:
      name: tudan
      password: 123456

# 服务注册到 eureka 注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8100/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:9100/eureka/
    # 因为该应用为服务提供者，是 eureka 的一个客户端，需要注册到注册中心
    register-with-eureka: true
    # 是否需要从 eureka 上检索服务
    fetch-registry: true
  instance:
    # 将自己的 ip 地址注册到 Eureka 服务中
    prefer-ip-address: true
    ip-address: 127.0.0.1
    # 指定实例 id
    instance-id: ${spring.application.name}###${server.port}