server:
  port: 7788

spring:
  application:
    # 指定服务名
    name: spring-cloud-learn2-config-server
  cloud:
    config:
      server:
        # 配置 git 仓库地址
        git:
          uri: https://github.com/tudan110/spring-cloud-learn2.git
          # 配置文件目录地址
          search-paths:
            - spring-cloud-learn2-config
          # 账号（公有项目不需要设置）
          #username: wtudan@126.com
          # 密码（公有项目不需要设置）
          #password: password
      # 分支
      label: master
  # RabbitMQ 相关的配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# 服务注册到 eureka 注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://tudan:123456@127.0.0.1:8100/eureka/,http://tudan:123456@127.0.0.1:9100/eureka/
    # 因为该应用为服务提供者，是 eureka 的一个客户端，需要注册到注册中心
    register-with-eureka: true
    # 是否需要从 eureka 上检索服务
    fetch-registry: true
  instance:
    # 将自己的 ip 地址注册到 Eureka 服务中
    prefer-ip-address: true
    # 指定实例 id
    instance-id: ${spring.application.name}###${server.port}
